//Natural Color (B4, B3, B2)
var rgb=ee.ImageCollection('LANDSAT/LC08/C02/T1_TOA')
 .filterDate('2022-06-01', '2022-09-30')
 .filter('CLOUD_COVER < 10')
 .select(['B4', 'B3', 'B2'])
 .filterBounds(ant_merkez)
print(rgb)
var rgbclip=rgb.mean().clip(ant_merkez)
Map.addLayer(rgbclip,"",'RGB')
//Color Infrared (B5, B4, B3)
var infrared=ee.ImageCollection('LANDSAT/LC08/C02/T1_TOA')
 .filterDate('2022-06-01', '2022-09-30')
 .filter('CLOUD_COVER < 10')
 .select(['B5', 'B4', 'B3'])
 .filterBounds(ant_merkez)
var infraredclip=infrared.mean().clip(ant_merkez)
Map.addLayer(infraredclip,"",'Infrared')
//Bathymetric (B4, B3, B1)
var bathymetric=ee.ImageCollection('LANDSAT/LC08/C02/T1_TOA')
 .filterDate('2022-06-01', '2022-09-30')
 .filter('CLOUD_COVER < 10')
 .select(['B4', 'B3', 'B1'])
 .filterBounds(ant_merkez)
var bathymetricclip=bathymetric.mean().clip(ant_merkez)
Map.addLayer(rgbclip,"",'Bathymetric')
Export.image.toDrive({ image:rgbclip,
 description:'Landsat8_infrared_ant_merkez',
 scale:10,
 region:ant_merkez,
})
